### Constants and Imports

In [1]:
pickle_rel_path = '../datasets/notmnist/notMNIST.pickle'
import os
import pickle
import matplotlib.pyplot as plt
import tensorflow as tf
import numpy as np

### Import or generate data

In [2]:
file_dir = os.path.dirname(os.path.realpath('__file__'))
pickle_path = os.path.abspath(os.path.join(file_dir, pickle_rel_path))
print('Pickle location:',pickle_path)

Pickle location: /home/lgessoni/repos/learning_ai/datasets/notmnist/notMNIST.pickle


In [3]:
with open(pickle_path,'rb') as file:
    datasets = pickle.load(file)
print(datasets.keys())

dict_keys(['train_dataset', 'valid_labels', 'test_labels', 'valid_dataset', 'train_labels', 'test_dataset'])


In [4]:
train_dataset = datasets['train_dataset']
train_labels = datasets['train_labels'] 
validate_dataset = datasets['valid_dataset']
validate_labels = datasets['valid_labels'] 
test_dataset = datasets['test_dataset']
test_labels = datasets['test_labels'] 

### -

In [7]:
node1 = tf.constant(3.0, dtype=tf.float32)
node2 = tf.constant(4.0) # also tf.float32 implicitly
node3 = tf.add(node1, node2)
sess = tf.Session()
print(sess.run(node3))

7.0


In [20]:
num_labels = 10
((np.arange(num_labels) == train_labels[:,None]).astype(np.float32))[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 1., 0.], dtype=float32)

In [51]:
np.array([1.,2.,3.,4.])[0:4:2]

array([1., 3.])

In [21]:
sample_shape = 

def activation(x):
    exp = tf.exp(x)
    return (exp/(exp+1))

def neuron(x):
    w = tf.get_variable("W", [1], dtype=tf.float64)
    b = tf.get_variable("b",[], dtype=tf.float64)
    return activation(W*x+b)

def loss(x):
    

In [26]:
a = activation([2.0,3.0])
sess = tf.Session()
sess.run(a)

array([0.8807971 , 0.95257413], dtype=float32)

0.8807971